services:
  gpo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: "postgres"
      DB_URL: "db:5432"
      DB_PASSWORD : ""
    ports:
      - "8081:8082"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gpo_net

  db:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gpo
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    networks:
      - gpo_net

networks:
  gpo_net:
    external: true