CREATE TABLE ACCOUNTS
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    HASH     VARCHAR(255) NOT NULL,
    EDIT     bool DEFAULT FALSE,
    ADMIN    bool DEFAULT FALSE,
    EMAIL    VARCHAR(255) NOT NULL

);

CREATE TABLE SESSIONS
(
    ID      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ACCOUNT INT NOT NULL
        CONSTRAINT ACCOUNT_RULE references accounts
);

CREATE TABLE ROUNDS
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE ROOMS
(
    ID    SERIAL PRIMARY KEY,
    FLOOR INT          NOT NULL,
    NAME  VARCHAR(255) NOT NULL
);

CREATE TABLE MATCHES
(
    ID                SERIAL PRIMARY KEY,
    NAME              VARCHAR(255) NOT NULL,
    ROUND             INT          NOT NULL
        CONSTRAINT ROUND_RULE REFERENCES rounds,
    COMPETITOR_AMOUNT INT          NOT NULL,
    START_TIME        TIME         NOT NULL,
    ROOM              INT          NOT NULL
        CONSTRAINT ROOM_RULE REFERENCES ROOMS

);

CREATE TABLE PARTICIPANTS
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    ACCOUNT  INT
        CONSTRAINT ACCOUNT_RULE REFERENCES accounts
);

CREATE TABLE MATCH_PARTICIPANTS
(
    ID          SERIAL PRIMARY KEY,
    MATCH       INT NOT NULL,
    CONSTRAINT MATCH_RULE FOREIGN KEY (MATCH) REFERENCES matches,
    PARTICIPANT INT NOT NULL,
    CONSTRAINT PARTICIPANT_RULE FOREIGN KEY (PARTICIPANT) REFERENCES participants,
    RANK        INT DEFAULT 0,
    constraint match_participants_pk
        primary key (participant, match)
);

CREATE TABLE NEXT_MATCHES
(
    ID         SERIAL PRIMARY KEY,
    MATCH      INT NOT NULL,
    CONSTRAINT MATCH_RULE FOREIGN KEY (MATCH) REFERENCES matches,
    NEXT_MATCH INT NOT NULL,
    CONSTRAINT NEXT_MATCH_RULE FOREIGN KEY (NEXT_MATCH) REFERENCES matches,
    RANK       INT NOT NULL
);

